### ISSUE TITLE
1499 bug

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#11]
the location of 1499 dimension allows players to shoot players on surface (this can only be achived if you have cola or increased 
time making its use in a real situation rare)

**Comment by galaxy119** [comment]
Doesn't it spawn you on the bottom side of an impassable cliff..?

**Comment by ZWRh3** [comment]
its an edge case if you have 4 colas you can get into a spot where you can shoot trough a wall in time

**Comment by galaxy119** [comment]
Shoot.. through.. a wall.. 

Gotta love northwood sometimes.

There's really no where else 1499 could send them that's more isolated, unfortunately, so I don't really think this would be possible to fix.

**Comment by ZWRh3** [comment]
you can send them even closer to edge (this spot is much further and cant be escaped quick enough)
![obrazek](https://user-images.githubusercontent.com/53602251/108848646-871f5100-75e1-11eb-8f6f-b7421d4518cd.png)

**Comment by galaxy119** [comment]
Can you send me the coords of that location?
