### ISSUE TITLE
quality of life changes

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#15]
blacklisted EMP doors config - probably make 106 room and gate A/B blacklisted by default

914  support - allow custom 914 recipes to either use or create custom items

equip message - toggleable for each item in settings same as pickup one but lasts only 1s mainly usefull due to situations like having lethal injection and adrenaline in invenory at once

make lethal injection use the adrenaline animation - it just waits and kills you without even touching you

**Comment by galaxy119** [comment]
All doors that require perms can already be 'blacklisted' with a config option.
Rest will be considered.

**Comment by ZWRh3** [comment]
i meant blacklisting specific doors
