### ISSUE TITLE
[suggestion] better custom item recognition

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#23]
when you pick up a custom item it says "you have picked up **a** CustomItemName" even if it should use **an** eg. emp

when you hold a custom item in hand it should say "you are holding a/an CustomItemName" toggleable for individual items as a property incase the showhint overwrites a different hint used by the item

dropping it should say "you have dropped a/an CustomItemName"

drop and equip dont say the description and the showhints are only 1s

**Comment by galaxy119** [comment]
It'd look extremely janky (code wise) to be able to determine if ``a`` should be ``an``. 

The new API will already have something show when you switch to a custom item in your inventory.
The new API will already have a way of changing the "You have picked up.." message.
