### ISSUE TITLE
shotgun may be broken

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#28]
i suspect the shotgun is broken i belive this because:

a **zombie** survived max ammo of point blank shots

unlimited SCP once temp removed a role due to a broken shotgun and readded it after fixing it

**Comment by ZWRh3** [comment]
(if this isnt a bug but the gun is so weak instead it needs a buff)

**Comment by galaxy119** [comment]
By default the Shotgun can only deal a maximum of 162 damage if all the shots it a player's body.
This value depends on both the base_damage config value and spread_count (multiply base_damage by spread_count to get the maximum body-shot damage)

SCP-049-2 by default has 300 health.
