### ISSUE TITLE
InsideLczWc broken i thonk

### ISSUE THREAD

**Issue by Inxity** [Exiled-Team/CustomItems#29]
lucky_cfg:
# How long the coin will stay spawned inside the PD.
  duration: 2
  # Where on the map items should spawn, and their % chance of spawning in each location.
  spawn_locations:
    InsideLczWc: 50
  # The Custom Item ID for this item.
  id: 5
  # The description of this item show to players when they obtain it.
  description: Bu eşyayı SCP-106'nın cep boyutunda yere atarsan büyülü olaylar yaşayabilirsin.
  # The name of this item shown to players when they obtain it.
  name: Şans Parası
  # How many of this item are allowed to naturally spawn on the map when a round starts. 0 = unlimited
  spawn_limit: 1
When i do the spawn chance 100 it still not spawns but if i set its spawnpoint to InsideGateA it works well

**Comment by galaxy119** [comment]
Can you confirm whether or not this issue is still present in ver 2.1.0? 
Also is it replicatable with other items, or just the coin?
