### ISSUE TITLE
EMP grenades should mess up all electronics

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#33]
now they only lock doors open and teleport 079 to its spawn many other electronic things such as tesla gates,radios,intercom and more are unaffected

**Comment by galaxy119** [comment]
Can add:
- Player's radios turn off if they are in the room when the EMP goes off.
- Flashlights held by players turn off when the EMP goes off.
- If the EMP is inside the intercom room the intercom resets.
- Tesla gates in affected rooms can be disabled.
