### ISSUE TITLE
EMP Grenade doesn't lock checkpoints

### ISSUE THREAD

**Issue by tpd1864blake** [Exiled-Team/CustomItems#50]
Doors that auto-close (Checkpoints and 106's doors) are not locked open. Instead, the door opens before automatically closing a few seconds later. After closing, the door will be locked closed for the remainder of the EMP's duration.

**Comment by joker-119** [comment]
Hm, I guess checkpoint doors don't obey the "NoPower" lock type when they are trying to close. I'll see what I can do.
