### ISSUE TITLE
scp-127 boosts all dmg caused by you while holding it

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#51]
**Describe the bug**
SCP-127 affects all dmg caused by you while holding it
**To Reproduce**
1. drink SCP-207
2. equip SCP-127

**Expected behavior**
damage multiplier only affects SCP-127

**Actual behaviour**
damage multiplier affects all dmg caused by you while holding SCP-127

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
N/A

**Results of `show plugins` command in console:**
N/A

**Additional context**
i have been unable to build the dll since im bad at that but this bug is blatant from the code alone as it happened many times before in this plugin (#7 being the first case)

(i know its ironic the first issue after making a bug report template terribly breaks it as it was found by reading the code alone but not having the compiled dll to test in game once again sorry)

**Comment by joker-119** [comment]
The checking for if the internal OnHurting event should be fired or not based on item and damage type should be handled by EXILED, I will forward this bug there and it will get looked into.
