### ISSUE TITLE
SCP-2818 isn't working

### ISSUE THREAD

**Issue by Raul125** [Exiled-Team/CustomItems#53]
**Describe the bug**
Shot the scp-2818, and it doesn't works.

**To Reproduce**
Shot an scp-2818.

**Server logs**
![image](https://user-images.githubusercontent.com/71040879/135760766-d3c467dd-09b4-4e08-8aea-32e4a38fd4e6.png)

**EXILED Version ("latest" is not a version):**
3.0.3-beta | 4.0.0 for CustomItems

**Results of `show plugins` command in console:**
I only have enabled CustomItems, i opened a server in local to test it.

**Additional context**
N/A

**Comment by joker-119** [comment]
Coulda sworn I fixed that, but will do the thing again.
