### ISSUE TITLE
EM-119 and IG-119 aren't exploding on collision

### ISSUE THREAD

**Issue by Raul125** [Exiled-Team/CustomItems#54]
**Describe the bug**
EM-119 and IG-119 aren't exploding on collision.

**To Reproduce**
Throw a EM-119/IG-119 grenade.

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured

**EXILED Version ("latest" is not a version):**
3.0.3-beta | 4.0.0 for CustomItems

**Results of `show plugins` command in console:**
I only have enabled CustomItems, i opened a server in local to test it.

**Additional context**
![image](https://user-images.githubusercontent.com/71040879/135761135-9b7a95f2-45d8-4bb3-9518-b2b792ed6c3b.png)
![image](https://user-images.githubusercontent.com/71040879/135761147-525de1f6-37cd-4f3f-9517-efcfc31bbfeb.png)

Also EM-119 isn't working on the surface.

**Comment by joker-119** [comment]
This is a known issue with EXILED itself, for some reason when I add a component to the grenade projectile, the component spits null ref errors every frame until it explodes. It's being looked into, but this is on EXILED to fix.
