### ISSUE TITLE
Duplicate items when player dies

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#62]
**Describe the bug**
If a player is holding a customitem and dies, they will drop two of the same things.

**To Reproduce**
Give yourself a CustomItem
Die in any way (I would jump down 939's pit)

**Expected behavior**
Expected to just drop everything the player was holding

**Server logs**
None relating to this, other then just me dying.

**EXILED Version ("latest" is not a version):**
3.7.2

**Results of `show plugins` command in console:**
Total: 20
Active: 20
Disabled: 0

**Additional context**

**Comment by joker-119** [comment]
Please provide pastebins of the server log files from rounds where this occurs, I need to see if there's any errors in the logs related to the plugin so I can debug this easier. Also the "Results of show plugins" gives you a list of all the plugins installed, this is also necessary incase another plugin is interfering with this one. 

It is important to provide all of the requested information in bug reports.

**Comment by DinoNuggets2** [comment]
Here is a log from me being killed with a Tranq Gun on me: https://pastebin.com/XF8kh18z

Here are all the plugins I have enabled: https://pastebin.com/a9TgggWJ
