### ISSUE TITLE
Grenade launcher will reload even with no grenades in inventory

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#64]
**Describe the bug**
Players can reload the grenade launcher with no grenades in their inventory, and sometimes if the player has grenades, they won't disappear from their inventory once reloaded (C4s, normal grenades, etc.)

**To Reproduce**
Get a grenade launcher
Reload with no grenades in inv.

**Expected behavior**
Expecting nothing to happen until you have a grenade in your inventory

**Server logs**
None

**EXILED Version ("latest" is not a version):**
3.7.2

**Results of `show plugins` command in console:**
Total: 20
Active: 20
Disabled: 0

**Additional context**

**Comment by joker-119** [comment]
Please provide pastebins of the server log files from rounds where this occurs, I need to see if there's any errors in the logs related to the plugin so I can debug this easier. Also the "Results of show plugins" gives you a list of all the plugins installed, this is also necessary incase another plugin is interfering with this one. 

It is important to provide all of the requested information in bug reports.
