### ISSUE TITLE
Grenade launcher launches 300 grenades

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#69]
**Describe the bug**
The grenade launcher will launch literally an entire arsenal of grenades(300) when using

**To Reproduce**
1. Use the first magazine in the grendae launcher
2. Reload and fire

**Expected behavior**
Expected to fire one grenade (or clip_size in configs)

**Server logs**
None

**EXILED Version ("latest" is not a version):**
4.1.7 (was happening before Christmas update)

**Results of `show plugins` command in console:**
                           **Enabled plugins: 29
                           Disabled plugins: 2
                           
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           SpectatorRange:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: spectator_range
                                - Priority: Higher
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.0.3.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           AutoFFToggle:
                                - Author: Kognity
                                - Version: 1.7.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: auto_f_f_toggle
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.6.0
                                - Required Exiled Version: 3.0.5
                                - Prefix: nuke_lock
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           Light Control:
                                - Author: Marco15453
                                - Version: 1.3.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: light_control
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 4.0.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK
                                - Version: 3.0.0.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: ST106
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           RemoteKeycard:
                                - Disabled
                                - Author: Beryl
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: remotekeycard
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           Scp008X:
                                - Author: DGvagabond
                                - Version: 3.1.0.0
                                - Required Exiled Version: 4.1.5
                                - Prefix: scp008_x
                                - Priority: Medium
                           MapEditorReborn:
                                - Disabled
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 1.3.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           CustomRoles:
                                - Author: Galaxy119
                                - Version: 2.0.0.0
                                - Required Exiled Version: 4.1.5
                                - Prefix: CustomRoles
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest**

**Additional context**

**Comment by joker-119** [comment]
Cannot replicate.

**Comment by DinoNuggets2** [comment]
Hm, that's weird. I'm not sure if I typed something wrong, but I don't think so. Should I send my config file for it or anything else?

**Comment by joker-119** [comment]
yea give me a pastebin with your plugin config file and a pastebin of the server log file

**Comment by joker-119** [comment]
Actually, this is probably because you are running a very outdated version of CustomItems. Please update to 5.0 and test again.

**Comment by DinoNuggets2** [comment]
Here's the Pastebin I have for the guns config:
https://pastebin.com/2m3335H0
And I'll also attach a video of what happens.

https://user-images.githubusercontent.com/91291118/146723324-77b6af2b-7e2f-4f14-b4ad-432fc92dc2a2.mp4

**Comment by DinoNuggets2** [comment]
I updated it to the latest release too*

**Comment by DinoNuggets2** [comment]
I found the issue, it is a compatibility issue with the SCP-008X plugin.
