### ISSUE TITLE
Modded grenades don't work

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#71]
**Describe the bug**
Every modded grenade just explodes like a normal grenade instead of doing its normal actions

**To Reproduce**
1. Give yourself a modded grenade (C4 or Implosion)
2. Throw grenade
**Expected behavior**
Expecting grenades to do what they are supposed to do (C4, stay put until the .det command is typed, and implosion pulls people towards it)

**Server logs**
Nothing in server logs that say anything about a grenade

**EXILED Version ("latest" is not a version):**
4.1.7

**Results of `show plugins` command in console:**

                           **Enabled plugins: 30
                           Disabled plugins: 1
                           
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           SpectatorRange:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: spectator_range
                                - Priority: Higher
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.0.3.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK
                                - Version: 3.0.0.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: ST106
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.6.0
                                - Required Exiled Version: 3.0.5
                                - Prefix: nuke_lock
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           Serpents Hand:
                                - Disabled
                                - Author: yanox, Michal78900 and Marco15453
                                - Version: 4.1.3
                                - Required Exiled Version: 4.1.7
                                - Prefix: serpents_hand
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 4.0.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           BetterDrops:
                                - Author: Jesus-QC
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7
                                - Prefix: better_drops
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           Scp008X:
                                - Author: DGvagabond
                                - Version: 3.1.0.0
                                - Required Exiled Version: 4.1.5
                                - Prefix: scp008_x
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 1.3.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           AutoFFToggle:
                                - Author: Kognity
                                - Version: 1.7.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: auto_f_f_toggle
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.1.7.0
                                - Required Exiled Version: 4.1.7.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest**

**Additional context**

**Comment by DinoNuggets2** [comment]
I was wrong about the C4, the C4's work fine

**Comment by Draconic99** [comment]
> I was wrong about the C4, the C4's work fine

it kinda works, it won't stick to walls if you have it enabled, however apart from that it works

**Comment by joker-119** [comment]
Can I get confirmation that there are still issues with grenades on exiled 5.0?
