### ISSUE TITLE
Error when someone dies while holding MediGun (MG-119)

### ISSUE THREAD

**Issue by EsserGaming** [Exiled-Team/CustomItems#72]
**Describe the bug**
~~When someone dies with medigun, an error occurs.~~ When someone leaves, an error occurs.

**To Reproduce**
1. Get medi gun
2. ~~die~~ Leave
3. See error

**Expected behavior**
No error

**Server logs**
LA Logs: https://pastebin.com/UWFVVuMT
Error: https://pastebin.com/rkin4PS0

**EXILED Version:**
Exiled.Loader - Version 4.2.1
Exiled.API - Version 4.2.2
Exiled.CreditTags - Version 4.2.2
Exiled.CustomItems - Version 4.2.2
Exiled.CustomRoles - Version 4.2.2
Exiled.Events - Version 4.2.2
Exiled.Permissions - Version 4.2.2

**Results of `show plugins` command in console:**
https://pastebin.com/uLHbwJUJ

**Comment by joker-119** [comment]
Already fixed in code, you can ignore this for now.
