### ISSUE TITLE
Some guns don't work properly

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#73]
**Describe the bug**
Some modded guns don't work as intended, so far I've found the Tranq gun and SCP-2818.

**To Reproduce**
1. Give yourself either a tranquilizer or SCP-2818
2. Shoot at someone

**Expected behavior**
Expecting SCP-2818 to shoot the player at the target, and the tranquilizer

**Server logs**
Pastebin was too large to self of LocalAdmin Logs

> [ERROR] [Exiled.Events] Method "OnInternalShooting" of the class "Exiled.CustomItems.API.Features.CustomWeapon" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler`1[[Exiled.Events.EventArgs.ShootingEventArgs, Exiled.Events, Version=4.2.3.0, Culture=neutral, PublicKeyToken=null]]"
> [2022-01-17 22:40:08.742 +00:00Z] [ERROR] [Exiled.Events] System.MissingMethodException: void PlayerStatsSystem.UniversalDamageHandler..ctor(single,PlayerStatsSystem.DeathTranslation,string)
>                                     at Exiled.CustomItems.API.Features.CustomWeapon.OnInternalShooting (Exiled.Events.EventArgs.ShootingEventArgs ev) [0x00014] in <2bc28af1821c44c5a327b0e94077bef5>:0 
>                                     at Exiled.Events.Extensions.Event.InvokeSafely[T] (Exiled.Events.Events+CustomEventHandler`1[TEventArgs] ev, T arg) [0x00024] in <f99ca7e469cc47b58b0c891c6be161bf>:0

**EXILED Version ("latest" is not a version):**
4.2.3

**Results of `show plugins` command in console:**
                           Enabled plugins: 30
                           Disabled plugins: 5
                           
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           CedMod:
                                - Disabled
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm
                                - Priority: Highest
                           Spectator Shooting Range:
                                - Author: rayzer
                                - Version: 2.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: spectator_shooting_range
                                - Priority: Higher
                           CedMod-Events:
                                - Disabled
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_events
                                - Priority: Medium
                           LightsRE:
                                - Author: Beryl - (Contributors: BuildBoy12)
                                - Version: 4.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: lights
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           Infiltrated:
                                - Author: Twitch.tv/Monaldcry7788#9248
                                - Version: 5.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: infiltrated
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Disabled
                                - Author: Michal78900
                                - Version: 4.0.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           SummonRespawnVehicles:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: summon_respawn_vehicles
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK
                                - Version: 3.0.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: ST106
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           CedMod-WebAPI:
                                - Disabled
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_WAPI
                                - Priority: Medium
                           CedMod-SampleEvent:
                                - Author: ced777ric#8321
                                - Version: 0.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_sampleevent
                                - Priority: Medium
                           Scp035:
                                - Disabled
                                - Author: Joker119
                                - Version: 4.0.2
                                - Required Exiled Version: 4.2.0
                                - Prefix: Scp035
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           BetterDrops:
                                - Author: Jesus-QC
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7
                                - Prefix: better_drops
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.8.2
                                - Required Exiled Version: 4.2.2
                                - Prefix: nuke_lock
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 2.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest

**Additional context**

**Comment by joker-119** [comment]
Plugin needs to be updated for 11.1.2, this likely won't happen until EXILED 5 releases

**Comment by DinoNuggets2** [comment]
Okay. Do you have an estimated time of when that will be out?

**Comment by DinoNuggets2** [comment]
Oh also, I found SCP-1499 and the Deflector Sheilds don't work.
