### ISSUE TITLE
Implosion grenade doesn't work

### ISSUE THREAD

**Issue by Draconic99** [Exiled-Team/CustomItems#75]
Describe the bug
When you throw the grenade, you won't and no one else will be pulled in by it

To Reproduce
Get implosion grenade
Throw implosion grenade
See the you aren't; sucked into it

Expected behavior
when you throw it, people in a certain radius will be sucked into it

**Comment by joker-119** [comment]
Use the actual entire bug report template, the information requested is not optional.
