### ISSUE TITLE
Grenades from grenade launcher do not explode upon contact of any surface

### ISSUE THREAD

**Issue by MasterRhino** [Exiled-Team/CustomItems#77]
**Describe the bug**
When the grenade launcher is being used, the grenades being shot from the launcher do not explode immediately upon coming into contact with a surface. Instead, grenades explode normally as if it was thrown by hand.

**To Reproduce**
Pick up or spawn Grenade Launcher
Pick up or spawn grenade
Load Grenade Launcher
Shoot Grenade Launcher

**Expected behavior**
For grenades to immediately explode when contact is made on any surface.

**Server logs**
Nothing in server logs

**EXILED Version ("latest" is not a version):**
5.0.0

**Results of `show plugins` command in console:**
Total Plugins: 9
Active Plugins: 9
Disabled Plugins: 0

**Additional context**
I also tried shortening the fuse timer to make the grenades explode quicker. I did this to see if that would fix the issue, but that didn't work either. I checked the configs to see if it was enabled. It says that it's suppose to explode immediately upon contact no matter what.

https://user-images.githubusercontent.com/100880816/156667891-74ba7bca-2b30-4a72-98b5-6a6397872ccb.mp4

**Comment by joker-119** [comment]
This is a known issue and will be addressed in EXILED itself at a later time.
