### ISSUE TITLE
Lethal Injection Animations

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#87]
Just a suggestion (not sure if this is a bug, don't want to fill out the entire bug template if it isn't a bug)

Make is so when taking a Lethal Injection, no matter the type of item, make it play the animation of taking it. 
(Please include 1853's animation for lean customitem)

**Comment by joker-119** [comment]
You can't do that. The animation is client side and can only play if they have the item related to said animation in their hand.
